#!/bin/bash

clear

cd /data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/ubuntu/home/user2

echo -e "\033[0;32m=== Sedang download file downgrade WPS Office 2019 ==="
echo -e "\033[0;37msilahkan tunggu.."

wget https://github.com/Pi-Apps-Coders/files/releases/download/large-files/wps-office_11.1.0.11720_arm64.deb
cd

proot-distro login ubuntu  -- bash -c "dpkg --configure -a; apt remove sudo -y; apt install sudo -y;exit"

clear

echo -e "\033[0;32mSedang proses install WPS Office 2019..."
echo " "
echo -e "\033[0;31mSilahkan Ketik angka Password :" "\033[0;32m123456" "\033[0;37mlalu ENTER di keyboard kalian"
echo "(password tidak terlihat, ketik aja terus enter)" 
echo " "

proot-distro login ubuntu --user user2 --shared-tmp -- bash -c "cd; sudo dpkg -i wps-office_11.1.0.11720_arm64.deb; exit"

wget -O - https://raw.githubusercontent.com/panjiades/Update2/refs/heads/main/UpdateFixWAweb | bash


clear

echo -e "\033[0;32m=== SELESAI ==="
echo -e "\033[0;30mUpdate fix kirim WA Web Selesai.., sekarang udah bisa kirim dokumen melalui Firefox Linux dan bisa dibuka di HP temen "
echo -e "\033[0;37mDowngrade ke WPS Office 2019 Selesai.."
echo -e "\033[0;30mUpdate fix kirim WA Web Selesai.., sekarang udah bisa kirim dokumen melalui Firefox Linux dan bisa dibuka di HP temen "
echo -e "\033[0;37mKeluarkan saja aplikasi termuxnya.."
echo -e "\033[0;37mAtau ketik" "\033[0;32mexit" "\033[0;37mlalu ENTER di keyboard" "\033[0;30mdi keyboard..."
