#!/bin/bash

termux-setup-storage && yes

termux-change-repo && yes

pkg update && yes | pkg upgrade
pkg install android-tools && yes
pkg install x11-repo && yes
pkg install termux-x11-nightly && yes
pkg install file && yes
pkg install pulseaudio && yes
pkg install virglrenderer-android && yes
pkg install proot-distro && yes
mkdir -pv /data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs
chmod 777 -R /data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs
mkdir .shortcuts
cd storage/downloads
mv Mulai.sh ~/.shortcuts
mv Matikan.sh ~/.shortcuts
mv Paket1.tar /data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs
cd
chmod +x .shortcuts/Mulai.sh
chmod +x .shortcuts/Matikan.sh
cd /data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs
tar xvf Paket1.tar
rm Paket1.tar
cd