#!/bin/bash


cd /data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/ubuntu/home/user2

ls -A

cd .local/share/mime/packages

ls

rm Override.xml

wget https://raw.githubusercontent.com/panjiades/Update2/refs/heads/main/Override.xml

cd

proot-distro login ubuntu --user user2 --shared-tmp -- bash -c "cd; update-mime-database -V ~/.local/share/mime/; exit"

clear

echo -e "\033[0;32m=== SELESAI ==="
echo -e "\033[0;30mUpdate fix kirim WA Web Selesai.., sekarang udah bisa kirim dokumen melalui Firefox Linux dan bisa dibuka di HP temen "
echo -e "\033[0;37mUpdate fix kirim WA Web Selesai..🥰, sekarang udah bisa kirim dokumen Word, Excel, Ppt melalui Firefox Linux dan bisa dibuka di HP temen🥰"
echo -e "\033[0;30mUpdate fix kirim WA Web Selesai.., sekarang udah bisa kirim dokumen melalui Firefox Linux dan bisa dibuka di HP temen "
echo -e "\033[0;37mKeluarkan saja aplikasi termuxnya.."
echo -e "\033[0;37mAtau ketik" "\033[0;32mexit" "\033[0;37mlalu ENTER di keyboard" "\033[0;30mdi keyboard..."

exit 1
