#!/bin/bash
pkg install wget -y

cd /data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/ubuntu/home/user2

ls -A

cd .local/share/mime/packages

ls

rm Override.xml

wget https://raw.githubusercontent.com/panjiades/Update2/refs/heads/main/Override.xml

cd

proot-distro login ubuntu --user user2 --shared-tmp -- bash -c "cd; update-mime-database -V ~/.local/share/mime/; exit"


echo -e "\033[0;32m=== SELESAI ==="
echo -e "\033[0;30mUpdate fix kirim WA Web Selesai.., sekarang udah bisa kirim dokumen melalui Firefox Linux dan bisa dibuka di HP temen "
echo -e "\033[0;37mUpdate fix kirim WA Web Selesai..🥰, sekarang udah bisa kirim dokumen melalui Firefox Linux dan bisa dibuka di HP temen🥰"
echo -e "\033[0;30mUpdate fix kirim WA Web Selesai.., sekarang udah bisa kirim dokumen melalui Firefox Linux dan bisa dibuka di HP temen "
echo -e "\033[0;37mUntuk keluar, silahkan ketuk tombol" "\033[0;32mENTER" "\033[0;37mdi keyboard..." "\033[0;30mdi keyboard..."

exit 1